import React from 'react';
import { View, Text, Pressable, ScrollView, Share, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';
import Svg, { Path } from 'react-native-svg';
import { Mascot } from '@/components/Mascot';
import { Icon, type IconName } from '@/components/Icon';
import { ICONS } from '@/theme/icon-map';
import type { AppNavigationProp } from '@/navigation/types';
import { colors } from '@/theme/colors';
import { useAuth } from '@/context/AuthContext';
import { useHealth } from '@/context/HealthContext';
import { useTheme } from '@/context/ThemeContext';

const ITEMS: { icon: IconName; text: string }[] = [
  { icon: ICONS.goalCycle, text: 'Summarize your menstrual cycle history' },
  { icon: ICONS.goalPregnancy, text: 'Export pregnancy and conception progress' },
  { icon: ICONS.note, text: 'Export formatted report for easy sharing and printing' },
  { icon: ICONS.doctor, text: 'Designed to support doctor visits with clear, organized health data' },
];

export function ExportReportScreen() {
  const navigation = useNavigation<AppNavigationProp>();
  const { userName, userEmail } = useAuth();
  const { periodDays, currentLog } = useHealth();
  const { themeColors } = useTheme();

  const handleGenerateReport = async () => {
    try {
      const reportText = `
=== CycleWise Health Report ===
User: ${userName || 'CycleWise User'} (${userEmail || 'N/A'})
Generated: ${new Date().toLocaleDateString()}

Logged Period Dates (${periodDays.length} total):
${periodDays.length > 0 ? periodDays.slice(-10).join(', ') : 'No recent period dates logged'}

Today's Health Logs:
- Weight: ${currentLog?.weight ?? 'Not recorded'} kg
- Temperature: ${currentLog?.temperature ?? 'Not recorded'} °C
- Sleep: ${currentLog?.sleep_minutes ?? 'Not recorded'} minutes
- Water Intake: ${currentLog?.water_ml ?? 'Not recorded'} ml
- Symptoms: ${currentLog?.symptoms?.join(', ') || 'None'}
- Moods: ${currentLog?.moods?.join(', ') || 'None'}
- Notes: ${currentLog?.note || 'None'}

Generated by CycleWise App — Empathetic Health Companion
      `.trim();

      await Share.share({
        title: 'CycleWise Doctor Report',
        message: reportText,
      });
    } catch (err: any) {
      Alert.alert('Report Error', err?.message || 'Unable to generate report at this time.');
    }
  };

  return (
    <View className="flex-1 bg-bg dark:bg-dark-bg">
      <View className="relative overflow-hidden" style={{ backgroundColor: colors.pinkPrimary }}>
        <SafeAreaView edges={['top']}>
          <View className="flex-row items-center justify-around pt-4 pb-16 px-6">
            <Pressable onPress={() => navigation.goBack()} className="absolute top-0 left-2 p-2 active:opacity-70">
              <Icon name={ICONS.back} size={22} color="white" />
            </Pressable>
            <Icon name={ICONS.avatar} size={56} color="white" />
            <View className="w-16 h-16 bg-white/30 rounded-2xl items-center justify-center">
              <Icon name={ICONS.download} size={28} color="white" />
            </View>
            <Icon name={ICONS.goalPregnancy} size={56} color="white" />
          </View>
        </SafeAreaView>
        <Svg style={{ position: 'absolute', bottom: 0, left: 0, width: '100%', height: 40 }} viewBox="0 0 375 40" preserveAspectRatio="none">
          <Path d="M0,0 Q187,40 375,0 L375,40 L0,40 Z" fill={themeColors.bg} />
        </Svg>
      </View>

      <ScrollView className="flex-1 px-4" contentContainerClassName="py-2 pb-24" showsVerticalScrollIndicator={false}>
        <View className="bg-card dark:bg-dark-card rounded-2xl p-5 shadow-sm border border-gray-100 dark:border-dark-border relative overflow-hidden">
          <View className="flex-row items-center justify-between mb-4">
            <Text className="text-base font-extrabold text-text dark:text-dark-text flex-1">
              Export report for the doctor
            </Text>
            <Mascot className="scale-75 -mr-2" />
          </View>

          {ITEMS.map((item) => (
            <View key={item.text} className="flex-row items-start gap-3 mb-4">
              <View className="w-10 h-10 rounded-full bg-pink-light dark:bg-dark-card-hover items-center justify-center">
                <Icon name={item.icon} size={18} color={colors.pinkDark} />
              </View>
              <Text className="text-sm font-semibold text-text dark:text-dark-text pt-2 flex-1">{item.text}</Text>
            </View>
          ))}
        </View>
      </ScrollView>

      <SafeAreaView edges={['bottom']} className="px-4 pt-4 bg-card dark:bg-dark-card border-t border-gray-100 dark:border-dark-border">
        <Pressable
          onPress={handleGenerateReport}
          className="w-full py-4 rounded-full bg-pink-primary items-center shadow-md mb-4 active:opacity-90"
        >
          <Text className="text-white font-bold text-base">Generate Report</Text>
        </Pressable>
      </SafeAreaView>
    </View>
  );
}
